### ISSUE TITLE
Pretrained Model Weights

### ISSUE THREAD

**Issue by sylviayuan-sy** [soon-yau/kpe#2]
Do you plan to release trained model weights?

**Comment by soon-yau** [comment]
Hi Sylvia, now that you ask, I'll release the weight. Need to tidy up things, so probably in a week's time.

**Comment by sylviayuan-sy** [comment]
Thank you so much for your quick response and help!!

**Comment by soon-yau** [comment]
I'm terribly sorry, I only managed to find time to do it now. I have updated README with instruction to download and run the model. If you need help to get some result/number, please let me know, I might be able to do them for you.
